# Generated by Django 4.2.27 on 2026-01-16 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifyConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Dify会话ID')),
                ('app_name', models.CharField(default='默认应用', max_length=255, verbose_name='应用名称')),
                ('app_api_key', models.TextField(verbose_name='应用API密钥（加密）')),
                ('dify_api_address', models.URLField(max_length=500, verbose_name='Dify API地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dify_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Dify对话会话',
                'verbose_name_plural': 'Dify对话会话',
                'db_table': 'dify_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DifyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dify消息ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_ai.difyconversation', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'Dify对话消息',
                'verbose_name_plural': 'Dify对话消息',
                'db_table': 'dify_message',
                'ordering': ['created_at'],
            },
        ),
    ]
